---
  detectors:
    IrresponsibleModule:
      enabled: false
  exclude_paths:
    - spec/helpers/database_helper.rb   # test helper file not considered
    - spec/helpers/vcr_helper.rb        # test helper file not considered
    - lib/*
