---
# Name your file secrets.yml

development:
  DB_FILENAME: db/local/dev.db
  API_KEY: create_google_apikey
  OPENAI_KEY: create_openai_apikey
  REPOSTORE_PATH: repostore
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: routeplanner
  CLONE_QUEUE_URL: https://sqs.<region>.amazonaws.com/<account-id>/<queue-name>

  # Application
  SESSION_SECRET: <some secret>

app_test:
  DB_FILENAME: db/local/test.db
  API_KEY:  create_google_apikey
  OPENAI_KEY: create_openai_apikey
  REPOSTORE_PATH: repostore
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: routeplanner
  CLONE_QUEUE_URL: https://sqs.<region>.amazonaws.com/<account-id>/<queue-name>
  # Application
  SESSION_SECRET: <some secret>
  
test:
  DB_FILENAME: db/local/test.db
  API_KEY:  create_google_apikey
  OPENAI_KEY: create_openai_apikey
  REPOSTORE_PATH: repostore
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: routeplanner
  CLONE_QUEUE_URL: https://sqs.<region>.amazonaws.com/<account-id>/<queue-name>
  # Application
  SESSION_SECRET: <some secret>

production:
  API_KEY:  create_google_apikey
  OPENAI_KEY: create_openai_apikey
  REPOSTORE_PATH: repostore
  API_HOST: 
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  CLONE_QUEUE: Queue Name
  CLONE_QUEUE_URL: https://sqs.<region>.amazonaws.com/<account-id>/<queue-name>
  SESSION_SECRET: <some secret>