---
# Name your file secrets.yml

development:
  DB_FILENAME: db/local/dev.db
  API_KEY: create_google_apikey
  # Application
  SESSION_SECRET: <some secret>

test:
  DB_FILENAME: db/local/test.db
  API_KEY:  create_google_apikey
  # Application
  SESSION_SECRET: <some secret>

production:
  API_KEY:  create_google_apikey
  # Application
  SESSION_SECRET: <some secret>