name: API continuous integration

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  api_test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos]
    runs-on: ${{ matrix.os }}-latest
    env:
      BUNDLE_WITHOUT: production
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Debug migrations
        run: ls -la db/migrations  # Check migration files

      - name: Check current migration version
        run: bundle exec rake db:version  # Check current migration version

      - name: Setup test database
        env:
            DB_FILENAME: ${{ secrets.DB_FILENAME }}
        run: RACK_ENV=test bundle exec rake db:migrate

      - name: Migrate down to version 4 (if required)
        run: |
          if bundle exec rake db:version | grep -q '6'; then
            echo "Migrating down to version 4"
            bundle exec rake db:migrate:down VERSION=4
          fi

      - name: Run all specs
        env:
          API_KEY: ${{ secrets.YT_KEY }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          DB_FILENAME: ${{ secrets.DB_FILENAME }}
          REPOSTORE_PATH: ${{ secrets.REPOSTORE_PATH }}
          API_HOST: ${{ secrets.API_HOST }}
        run: bundle exec rake spec
